--- #YAML:1.0
name:               Apache-Gallery
version:            1.0.2
abstract:           mod_perl handler to create an image gallery
author:
    - Michael Legart <michael@legart.dk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:             3.08
    File::Spec:      0
    Image::Imlib2:   1.02
    Image::Info:     0
    Image::Size:     0
    Test::More:      0
    Text::Template:  0
    URI:             1.23
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
